"""
Depth-integrated NPP (TOT_PROD) time-mean maps from zsliced dia files.
3x2 layout: top-left = no tides, no WEC (absolute); other five panels =
difference from that reference.  ampwec panel shows placeholder if its
zslice dia files have not yet been generated by zslice_npp.py.

Each scenario's NPP is a per-file grand mean over its entire zslice dia
record (same method as postprocessing/profile_zslice_par.py) — no
cross-scenario date matching. notideswec/ampwec/tidesampwec write two
12-hour dia_avg files per day while the other scenarios write one true
24-hour average per day; per-file weighting over the full record is
diel-representative for both cadences.
"""

import os
import glob
import numpy as np
from netCDF4 import Dataset
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
from cartopy.mpl.ticker import LongitudeFormatter, LatitudeFormatter
import cmocean

ZSLICE_ROOT  = '/data/project1/minnaho/swel/zslicefull'
ZSLICE_DIRS  = {'ampwec': 'notidesampwec'}   # label → zslice subdirectory (identity for tidesampwec)
GRD         = 'mc60_grd.nc'
CACHE       = './figs/npp_depth_integrated_cache.npz'
DZ          = 2.0   # m — uniform dia z-grid (0 to -200 m every 2 m)
REF         = 'notidesnowec'

XLIM = [-122.4, -121.78]
YLIM = [36.47, 37.06]

LON_TICKS = np.array([-122.4, -122.1, -121.8])
LAT_TICKS = np.array([36.47, 36.6, 36.8, 37.0])

SCENARIOS = ['notidesnowec', 'tideswec', 'tidesnowec', 'notideswec', 'ampwec', 'tidesampwec']
LABELS = {
    'notidesnowec': 'no tides, no WEC',
    'tideswec':     'tides, WEC',
    'tidesnowec':   'tides, no WEC',
    'notideswec':   'no tides, WEC',
    'ampwec':       'no tides, 2.5x WEC',
    'tidesampwec':  'tides, 2.5x WEC',
}


def _fill_to_nan(arr):
    return np.where(np.abs(arr) > 1e30, np.nan, arr)


def list_zfiles(scen):
    sd = ZSLICE_DIRS.get(scen, scen)
    return sorted(glob.glob(f'{ZSLICE_ROOT}/{sd}/dia/z_mc60_bgc_dia_avg.*.nc'))


def load_npp(zfiles):
    """Grand mean of depth-integrated TOT_PROD over all zslice files. Returns (eta, xi)."""
    if not zfiles:
        return None
    s = c = None
    for zf in zfiles:
        with Dataset(zf) as nc:
            arr = _fill_to_nan(np.array(nc.variables['TOT_PROD'][:]))  # (z, eta, xi)
        di      = np.nansum(arr, axis=0) * DZ * 86400.0                 # (eta, xi), s→d
        chunk_c = (~np.isnan(arr)).any(axis=0).astype(np.int64)
        if s is None:
            s, c = di, chunk_c
        else:
            s += di
            c += chunk_c
    return np.where(c > 0, s / np.maximum(c, 1), np.nan)


# ==========================================
# Load / cache
# ==========================================
npp = None
if os.path.exists(CACHE):
    cc = np.load(CACHE, allow_pickle=True)
    cached = {}
    valid = True
    for scen in SCENARIOS:
        if scen not in cc:
            valid = False
            break
        arr = cc[scen]
        # allow None (stored as 0-d object array) or 2D
        if arr.ndim == 0:
            cached[scen] = None
        elif arr.ndim == 2:
            cached[scen] = arr
        else:
            valid = False
            break
    if valid:
        npp = cached
        print(f'Loaded cache from {CACHE}')
    else:
        print('Cache incomplete or shape mismatch — recomputing')

if npp is None:
    npp = {}
    for scen in SCENARIOS:
        zfiles = list_zfiles(scen)
        if not zfiles:
            print(f'No zslice dia files for: {scen} — panel will be blank. '
                  f'Run zslice_npp.py for this scenario first.')
            npp[scen] = None
            continue
        print(f'  [{scen}] {len(zfiles)} files -> loading ...')
        npp[scen] = load_npp(zfiles)

    # Save cache — None stored as object array so npz can hold it
    save_dict = {}
    for scen in SCENARIOS:
        save_dict[scen] = npp[scen] if npp[scen] is not None else np.array(None, dtype=object)
    np.savez(CACHE, **save_dict)
    print(f'Saved cache -> {CACHE}')

# ==========================================
# Grid
# ==========================================
grd      = Dataset(GRD)
lon_rho  = np.array(grd.variables['lon_rho'])
lat_rho  = np.array(grd.variables['lat_rho'])
mask_rho = np.array(grd.variables['mask_rho'])
land     = np.where(mask_rho == 0, 1.0, np.nan)

# colour limits (exclude missing scenarios)
ref_data  = npp[REF]
vmax_abs  = np.nanpercentile(ref_data, 99)
diff_arrs = [(100.0 * (npp[s] - ref_data) / ref_data).ravel()
             for s in SCENARIOS if s != REF and npp[s] is not None]
all_diffs = np.concatenate(diff_arrs) if diff_arrs else np.array([0.0])
vmax_diff = np.nanpercentile(np.abs(all_diffs[np.isfinite(all_diffs)]), 99)

# ==========================================
# 3×2 figure layout
# ==========================================
plt.rcParams.update({'font.size': 14})

proj = ccrs.PlateCarree()
fig, axes = plt.subplots(3, 2, figsize=(10, 13),
                         subplot_kw=dict(projection=proj),
                         gridspec_kw=dict(hspace=0.15, wspace=0.4))

# (ax, scen, is_diff, show_lat, show_lon)
panels = [
    (axes[0, 0], REF,            False, True,  False),
    (axes[0, 1], 'notideswec',   True,  False, False),
    (axes[1, 0], 'tideswec',     True,  True,  False),
    (axes[1, 1], 'tidesnowec',   True,  False, False),
    (axes[2, 0], 'tidesampwec',  True,  True,  True),
    (axes[2, 1], 'ampwec',       True,  False, True),
]

pc_abs = pc_diff = None
for ax, scen, is_diff, show_lat, show_lon in panels:
    if is_diff:
        title = LABELS[scen]
    else:
        title = LABELS[REF]
    ax.set_title(title, fontsize=13)

    if npp[scen] is None:
        ax.text(0.5, 0.5, 'zslice data\nnot yet available',
                transform=ax.transAxes, ha='center', va='center',
                fontsize=12, color='gray')
        ax.set_extent([XLIM[0], XLIM[1], YLIM[0], YLIM[1]], crs=proj)
    else:
        if is_diff:
            data       = 100.0 * (npp[scen] - ref_data) / ref_data
            cmap       = cmocean.cm.balance
            vmin, vmax = -vmax_diff, vmax_diff
        else:
            data       = npp[REF]
            cmap       = cmocean.cm.algae
            vmin, vmax = 0, vmax_abs

        pc = ax.pcolormesh(lon_rho, lat_rho, data,
                           cmap=cmap, vmin=vmin, vmax=vmax,
                           transform=proj, shading='nearest')
        ax.pcolormesh(lon_rho, lat_rho, land, cmap='gray', vmin=0, vmax=1,
                      transform=proj, shading='nearest', zorder=2)
        ax.contour(lon_rho, lat_rho, mask_rho, levels=[0.5],
                   colors='k', linewidths=0.5, transform=proj, zorder=3)
        ax.set_extent([XLIM[0], XLIM[1], YLIM[0], YLIM[1]], crs=proj)

        if is_diff:
            pc_diff = pc
        else:
            pc_abs = pc

    ax.set_xticks(LON_TICKS, crs=proj)
    ax.set_yticks(LAT_TICKS, crs=proj)
    ax.xaxis.set_major_formatter(LongitudeFormatter())
    ax.yaxis.set_major_formatter(LatitudeFormatter())
    ax.tick_params(labelbottom=show_lon, labelleft=show_lat, labelsize=13)

# ==========================================
# Colorbars
# ==========================================
fig.canvas.draw()

# abs: right of [0,0], spanning only that panel
pos00 = axes[0, 0].get_position()
cax_abs = fig.add_axes([pos00.x1 + 0.02, pos00.y0, 0.02, pos00.y1 - pos00.y0])
if pc_abs is not None:
    fig.colorbar(pc_abs, cax=cax_abs, orientation='vertical',
                 label=r'$\int$NPP (mmol m$^{-2}$ d$^{-1}$)')

# diff: right of col 1, spanning all three rows
pos_top = axes[0, 1].get_position()
pos_bot = axes[2, 1].get_position()
cax_diff = fig.add_axes([pos_top.x1 + 0.02, pos_bot.y0, 0.02, pos_top.y1 - pos_bot.y0])
if pc_diff is not None:
    fig.colorbar(pc_diff, cax=cax_diff, orientation='vertical',
                 label='% change from no tides, no WEC')

out = './figs/npp_depth_integrated.png'
plt.savefig(out, bbox_inches='tight', dpi=600)
print(f'saved -> {out}')
